version: '2.4'

services:
  certbot:
    image: certbot/certbot:latest
    ports:
      - "80:80"
    volumes:
      - cert-etc:/etc/letsencrypt
      - cert-var-lib:/var/lib/letsencrypt
  manage-users:
    build: srv.d/calibre
    command: calibre-server --manage-users --userdb user.db
    image: quay.io/cli-tools/calibre:latest
    stdin_open: true
    tty: true
    volumes:
      - books:/books
      - config:/config
