version: '2.4'

services:
  nginx:
    build:
      context: srv.d/nginx
      args: [ build=$build ]
  server:
    build:
      context: srv.d/calibre
      args: [ build=$build ]
    image: quay.io/cli-tools/calibre:latest
    init: true
    volumes:
      - config:/config
      - books:/books
  mobile:
    build:
      context: srv.d/calibre
      args: [ build=$build, service=mobile ]
    image: quay.io/cli-tools/calibre:mobile
    init: true
    volumes:
      - config:/config
      - books:/books

volumes:
  books: {}
  config: {}
  cert-etc: {}
  cert-var-lib: {}
