version: '2.4'

services:
  nginx:
    build: srv.d/nginx
    ports:
     - "443:443"
    volumes:
      - cert-etc:/etc/letsencrypt
      - cert-var-lib:/var/lib/letsencrypt
    hostname: $HOSTNAME
    domainname: $DOMAINNAME
  server:
    build:
      context: srv.d/calibre
      args: [ build=auth ]
    image: quay.io/cli-tools/calibre:latest
    init: true
    volumes:
      - config:/config
      - books:/books
  mobile:
    build:
      context: srv.d/calibre
      args: [ build=mobile ]
    image: quay.io/cli-tools/calibre:mobile
    init: true
    volumes:
      - config:/config
      - books:/books

volumes:
  books: {}
  config: {}
  cert-etc: {}
  cert-var-lib: {}
