version: '2.4'

services:
  nginx:
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - cert-etc:/etc/letsencrypt
      - cert-var-lib:/var/lib/letsencrypt
    hostname: $HOSTNAME
  server:
    restart: unless-stopped
  mobile:
    restart: unless-stopped
